# Generated by Django 4.1.7 on 2023-02-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoryMany',
            field=models.ManyToManyField(blank=True, null=True, to='ProductApp.category'),
        ),
    ]
